import './globals.scss'
import { Inter } from 'next/font/google'
import Header from '../components/header/header';
// import Cursor from '../components/cursor/cursor';
const inter = Inter({ subsets: ['latin'] })
import MouseFollower from "mouse-follower";
import gsap from "gsap";

MouseFollower.registerGSAP(gsap);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Temporarily disable cursor until we have the sticky element */}
        {/* <Cursor /> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
